### ISSUE TITLE
Change the scim2 documentation URI

### ISSUE THREAD

**Issue by nilasini** [wso2/docs-is#1001]
**Description:**
**Description:**
When SCIM 2.0 REST APIs doc for IS5.9.0 is ready then change the below key.

`scim2.documentation_uri`

Moved from https://github.com/wso2-extensions/identity-inbound-provisioning-scim2/issues/181

**Comment by gomathyk** [comment]
In https://is.docs.wso2.com/en/5.9.0/develop/using-the-scim-2.0-rest-apis/, 

When the request is, 
`curl -v -k --user admin:admin  https://localhost:9443/scim2/ServiceProviderConfig`

The response is given as 
`{"patch":{"supported":true},"filter":{"maxResults":200,"supported":true},"documentationUri":"http://example.com/help/scim.html","authenticationSchemes":[{"name":"OAuth Bearer Token","description":"Authentication scheme using the OAuth Bearer Token Standard","specUri":"http://www.rfc-editor.org/info/rfc6750","type":"oauthbearertoken","primary":true},{"name":"HTTP Basic","description":"Authentication scheme using the HTTP Basic Standard","specUri":"http://www.rfc-editor.org/info/rfc2617","type":"httpbasic","primary":false}],"schemas":["urn:ietf:params:scim:schemas:core:2.0:ServiceProviderConfig"],"etag":{"supported":false},"sort":{"supported":false},"bulk":{"maxPayloadSize":1048576,"maxOperations":1000,"supGomathys-`

The value for the documentationUri is http://example.com/help/scim.html, which is an example domain. This needs to be changed into a scim2 sepcific uri. Since it is a config change transferring it.
