### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by askya** [wso2/docs-is#1174]
Location : https://is.docs.wso2.com/en/latest/get-started/provisioning-architecture/
Hello!
Please it is unnoticeable but as feedback, it can help.
In image https://is.docs.wso2.com/en/latest/assets/img/getting-started/charon-module-breakdown.png, in samples box, **instead of ****provider** we have **provder**.

Thanks for the work!

**Comment by omindu** [comment]
Thanks for reporting this.

@gomathyk @sherenewso2 Can you update the doc with the below image ?

![image](https://user-images.githubusercontent.com/9883427/74526084-9ee0e580-4f48-11ea-87c8-2da3c0c6c1de.png)

**Comment by askya** [comment]
Please look at the commit at https://github.com/wso2/docs-is/commit/1f5966755929411cb43397ba4204dc21de8ba892

The old image path is ../assets/img/getting-started/charon-module-breakdown.png but the new one is hosted on github.
How can I bring the new one to the directory?

**Comment by sherenewso2** [comment]
Thank you for your contribution! The old image was placed in the [assets/img/getting-started/ folder](https://github.com/wso2/docs-is/tree/5.9.0/en/docs/assets/img/getting-started) so the new image was updated and uploaded to the same directory. 

This is now fixed in [1]

[1] https://is.docs.wso2.com/en/latest/get-started/provisioning-architecture/
