### ISSUE TITLE
Terminology inconsistency

### ISSUE THREAD

**Issue by isharanaotunna** [wso2/docs-is#119]
Certain sections say Entitlement management [1]. Product admin guide says Identity administration. 

![Screen Shot 2019-08-31 at 12 26 45 PM](https://user-images.githubusercontent.com/54733286/64060482-a6a30c80-cbea-11e9-9983-a073b126b472.png)

[1] https://is.docs.wso2.com/en/5.9.0/getting-started/access-control-and-entitlement-management/

The IS product page mentions Account Management and Identity provisioning which encompasses both. Can we use the industry wide terminology? Or do these mean different things?

**Comment by gomathyk** [comment]
Access Control and Entitlement Management deals with the access rights given to a particular resource which is mostly an application, and the docs mostly speak of how the xacml policies help with the authorization. 

Identity provisioning, on the other hand, is to do with managing a user's access, i.e., the privileges he has depending on his role, and work flows where multiple users are involved in the same task. This basically tells us how an admin can manage his users and their roles. 

There isn't an industry wide term AFAIK. From what I saw, the terms are different from product to product ranging from delegated administration, role-based access control, provisioning ,user management, and fine grained access control. 

Closing this issue since there isn't a certain standard terminology that we can adopt and the existing ones are almost similar to the ones in use across the industry.
