### ISSUE TITLE
"Add role using SOAP" links not working

### ISSUE THREAD

**Issue by Yasara-Y** [wso2/docs-is#127]
**Description:**
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/configuring-roles-and-permissions/#add-role-using-soap

The link "Calling Admin Services" directs to an error page.

**Suggested Labels:**
type Bug

![Screenshot from 2019-08-31 12-53-47](https://user-images.githubusercontent.com/51709964/64060796-33e86000-cbef-11e9-89ec-9ae72e8a83e3.png)

**Comment by deshankoswatte** [comment]
Hi @Yasara-Y,

This is fixed in [1] as shown in the screen record below. Hence closing the issue.

![Peek 2019-11-25 10-12](https://user-images.githubusercontent.com/33062368/69512954-26334400-0f6c-11ea-9621-27d59afc520c.gif)

[1] - https://is.docs.wso2.com/en/5.9.0/learn/configuring-roles-and-permissions/#add-role-using-soap
