### ISSUE TITLE
Formatting issue in "Configuring SAML2 Web Single Sign On"

### ISSUE THREAD

**Issue by dewniMW** [wso2/docs-is#163]
**Description:**
Formatting issue at [1]

![image](https://user-images.githubusercontent.com/24982871/64072970-3ad9a600-ccb5-11e9-9c12-9bba7ee0392b.png)

[1] https://is.docs.wso2.com/en/5.9.0/tutorials/configuring-SAML2-Web-Single-Sign-On/

**Comment by deshankoswatte** [comment]
Hi @dewniMW,

This is fixed in [1] as shown below in the screenshot. Hence closing this issue.

![Screenshot from 2019-11-24 19-22-16](https://user-images.githubusercontent.com/33062368/69495697-d44cd880-0eef-11ea-91d2-89951f94a542.png)

[1] - https://is.docs.wso2.com/en/5.9.0/learn/configuring-saml2-web-single-sign-on/
