### ISSUE TITLE
The line is mentioned as collapse link, but it is not working as expected.

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#187]
Suggested Labels
Affected/IS5.9.0

document: Writing an Outbound Provisioning Connector
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/writing-an-Outbound-Provisioning-Connector/

![image](https://user-images.githubusercontent.com/39120228/64334657-a2199200-cff6-11e9-81cc-5347d51b7c09.png)

**Comment by deshankoswatte** [comment]
Hi @NilukaSripalim, 

This is fixed in [1]. The below screenshot provides evidence. Hence closing the issue.

![Screenshot from 2019-11-24 11-25-42](https://user-images.githubusercontent.com/33062368/69490410-68498080-0ead-11ea-8bc4-f7c3173210f7.png)

[1] - https://is.docs.wso2.com/en/5.9.0/develop/writing-an-outbound-provisioning-connector/
