### ISSUE TITLE
Sidebar (Side Navigation) menus are not displaying in "Writing an Outbound Provisioning Connector"

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#188]
Suggested Labels
Affected/IS5.9.0

document: https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/writing-an-Outbound-Provisioning-Connector/

**Comment by deshankoswatte** [comment]
Hi @NilukaSripalim,

This is fixed in [1] as shown below in the screenshot. Hence closing this issue.

![Screenshot from 2019-11-25 11-48-47](https://user-images.githubusercontent.com/33062368/69517039-90061a80-0f79-11ea-9e6a-bf05d04f1f96.png)

[1] - https://is.docs.wso2.com/en/5.9.0/develop/writing-an-outbound-provisioning-connector/

**Comment by omindu** [comment]
Thanks @deshankoswatte
