### ISSUE TITLE
collapse link is not working as expected. 

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#197]
Suggested Labels
Affected/IS5.9.0

document: Installing as a Windows Service
https://is.docs.wso2.com/en/5.9.0/admin-guide/installing-as-a-Windows-Service/

![image](https://user-images.githubusercontent.com/39120228/64412243-9ab4c000-d0ac-11e9-9239-321f0fdb0caf.png)

**Comment by deshankoswatte** [comment]
Hi @NilukaSripalim,

This is fixed in [1] as shown in the screenshot below. Hence closing this issue.

![Screenshot from 2019-11-25 10-04-55](https://user-images.githubusercontent.com/33062368/69512736-2d0d8700-0f6b-11ea-82d7-ce9a1eae7bbc.png)

[1] - https://is.docs.wso2.com/en/5.9.0/setup/installing-as-a-windows-service/
