### ISSUE TITLE
Directing to Page Not found page from Provisioning architecture page

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#207]
**Suggested Labels**
Affected /IS 5.9.0

Directing to Page Not Found page from Provisioning Architecture Page. When Click on **SCIM 1.1 APIs** hyperlink it will direct to a page not found page.

[1]. https://is.docs.wso2.com/en/5.9.0/getting-started/provisioning-architecture/

**Comment by deshankoswatte** [comment]
Hi @ShanikaWickramasinghe,

This is fixed in [1] as shown in the below screen record. Hence closing the issue.

![Peek 2019-11-24 19-38](https://user-images.githubusercontent.com/33062368/69495886-16771980-0ef2-11ea-941d-2b53ff4ffd37.gif)

[1] - https://is.docs.wso2.com/en/5.9.0/get-started/provisioning-architecture/
