### ISSUE TITLE
Link navigate to empty page

### ISSUE THREAD

**Issue by NilukaSripalim** [wso2/docs-is#216]
Suggested Labels
Affected/IS5.9.0

document: Identity Provider Configurations used with APIs
https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/identity-Provider-Configurations-used-with-APIs/

![image](https://user-images.githubusercontent.com/39120228/64527442-90e8c200-d323-11e9-86e3-52f60441f124.png)

**Comment by deshankoswatte** [comment]
Hi @NilukaSripalim,

This is fixed in [1] as shown below in the screen record. Hence closing this issue.

![Peek 2019-11-24 19-33](https://user-images.githubusercontent.com/33062368/69495836-7caf6c80-0ef1-11ea-8310-f33595e2632c.gif)

[1] - https://is.docs.wso2.com/en/5.9.0/develop/writing-a-custom-federated-authenticator/
