### ISSUE TITLE
Blank Space without content in Work Flow management page

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [wso2/docs-is#227]
Affected/ IS 5.9.0

Unnecessary blank space is available in work flow management page.

![wf](https://user-images.githubusercontent.com/31848014/64588843-3605a800-d3c1-11e9-8bcc-c4fff62be153.png)

[1]. https://is.docs.wso2.com/en/5.9.0/using-wso2-identity-server/workflow-management/

**Comment by deshankoswatte** [comment]
Hi @ShanikaWickramasinghe,

This is fixed in [1] as shown in the screenshot below. Hence closing this issue.

![Screenshot from 2019-11-25 11-56-11](https://user-images.githubusercontent.com/33062368/69517442-c001ed80-0f7a-11ea-858a-37cdfc34bbbf.png)

[1] - https://is.docs.wso2.com/en/5.9.0/learn/workflow-management/

**Comment by omindu** [comment]
Thanks @deshankoswatte
