### ISSUE TITLE
Broken link for "Working with Entitlement" in https://is.docs.wso2.com/en/5.9.0/get-started/architecture/

### ISSUE THREAD

**Issue by janakamarasena** [wso2/docs-is#280]
**Description:**
Broken link for "Working with Entitlement" in https://is.docs.wso2.com/en/5.9.0/get-started/architecture/

<img width="1067" alt="Screen Shot 2019-09-17 at 1 05 35 PM" src="https://user-images.githubusercontent.com/11583571/65021051-00763700-d94c-11e9-8057-4f6997b97c2e.png">

**Comment by deshankoswatte** [comment]
Hi @janakamarasena,

This is fixed in [1]. The screen record below provides evidence. Hence closing this issue. 

![Peek 2019-11-24 11-36](https://user-images.githubusercontent.com/33062368/69490526-5ff24500-0eaf-11ea-9a1e-e1122b2b19b9.gif)

[1] - https://is.docs.wso2.com/en/5.9.0/get-started/architecture/
