### ISSUE TITLE
React sample SDK Redirecting to the Login page after login

### ISSUE THREAD

**Issue by divyaamunugama** [wso2/docs-is#3241]
**Description:**

Issue 1: 
After the user login to the application by entering credentials, the user will get redirected to the same login page.
![image](https://user-images.githubusercontent.com/84217321/183857616-4ea70915-7c9d-4702-9cfd-a7e83b2fa948.png)

Issue 2:
The port number of the SDK should be updated to `3000`.
![image](https://user-images.githubusercontent.com/84217321/183858231-0d927496-fa55-4943-8fdf-e8486ea2d1a3.png)

How to reproduce the issue:
https://is.docs.wso2.com/en/6.0.0/sdks/start-integrating-apps/integrate-a-react-app/

**Comment by brionmario** [comment]
Since we run the application on `https://localhost:3000`, IS blocks the JWKS cross-origin request.

<img width="803" alt="Screenshot 2022-08-10 at 16 44 48" src="https://user-images.githubusercontent.com/25959096/183887844-616e074f-680c-4201-9fb6-02bac60e411d.png">

We need to allow `https://localhost:3000` as  a CORS origin on the Identity Server.

**Comment by brionmario** [comment]
## Additional suggestions

1. Add instructions to select only `authorization_code` & `refresh_token`.
2. Make PKCE mandatory (SPA best practice for code flow)
3. Disable `supportPlainTransformAlgorithm`.

**Comment by divyaamunugama** [comment]
Fixed with https://github.com/wso2/docs-is/pull/3242
