### ISSUE TITLE
Claim mapping for SCIM provisioning to AD needs an update

### ISSUE THREAD

**Issue by ajanthan** [wso2/docs-is#993]
Location : https://is.docs.wso2.com/en/5.9.0/learn/configuring-active-directory-user-stores-for-inbound-provisioning/

There are two issues with this page.

1. The screenshot(and guide) for updating claim mapping is wrong. The final update should be done in the default claim dialect. Not in the SCIM dialect.

2. resourceType is a new claim present in SCIM request. It also needs to be mapped existing AD attribute

**Comment by gomathyk** [comment]
This document was outdated. Have included the updated document now. 
https://is.docs.wso2.com/en/5.9.0/learn/configuring-user-stores-for-scim-1.1-based-inbound-provisioning/

1. The screenshot has been updated now. 

2. resourceType is not mapped because it is not in the scim 1.1 specification and we do not receive it as part of the scim 1.1 schema. This has been mapped for scim 2 active directory though and the details can be found in https://is.docs.wso2.com/en/5.9.0/learn/configuring-active-directory-user-stores-for-scim-2.0-based-inbound-provisioning/.
